### ISSUE TITLE
[Rails] Add ability to delete media for Speaker when uploaded

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#521]
## Context:
In Terrastories, it is possible to add media assets (such as photos, videos, and audio) to various data models. For `Speaker`, it is possible to add a photo. However, while it is currently possible to replace the photo, it is not possible to remove it altogether. We should have a `Remove` button for Speaker photos much like we have one for media assets in Places or Stories.

## Acceptance criteria:
- [ ] When an admin user adds an image to a `Speaker`, and the user goes to the edit view, the user sees a `Remove` button underneath the media upload.
- [ ] When the user clicks the `Remove` button, the media asset is removed from the edit view.
- [ ] When the user saves the data, the media asset no longer shows up on the front end view of that data (i.e. `/home`) or in any Administrate views.
- [ ] The media asset is also removed from ActiveStorage.
- [ ] Existing tests do not break

**Comment by marcushwz** [comment]
Hi, I am Marcus from Malaysia. Just found out `Hacktoberfest` and would love to contribute to this issue. Is this issue still available for grab? Thanks and have a great day!

**Comment by mirandawang** [comment]
Hi @marcushwz , apologies for the delay in response. You are definitely welcome to work on this! Let us know if you have any questions. Thanks!  :D

**Comment by claracavalcante** [comment]
Hello! If this issue still needs work, I would like to work on it :)

**Comment by rudokemper** [comment]
Sure, @claracavalcante! I will assign you :)

**Comment by julinvictus** [comment]
@claracavalcante @rudokemper, ok if I give it a try?

**Comment by claracavalcante** [comment]
@julinvictus absolutely! I ended up not being able to tackle it yet.

**Comment by rudokemper** [comment]
Thanks @claracavalcante! And assigning you, @julinvictus :)
