### ISSUE TITLE
[Custom themes] Let's make it possible to set the map center, extent, zoom, pitch, and bearing for a community in Theme

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#587]
Now that we have a Theme model in Rails, let's make it possible to set the default map center, boundaries, zoom, pitch, and bearing for a community. Currently, these are hard coded in `Map.jsx`.

## Acceptance criteria:
- [ ] Admin user logs into Terrastories and goes to the Theme menu.
- [ ] There are fields for 
    * center latitude and longitude
    * southwest boundary latitude and longitude
    * northeast boundary latitude and longitude
    * zoom level
    * pitch
    * bearing
- [ ] Entering values for these overrides whatever is set in `Map.jsx`.
- [ ] Add validation tests for each field:
    * Center `latitude` is between -90 and 90, `longitude` is between -180 and 180.
    * Southwest boundary `latitude` is between -90 and 90, `longitude` is between -180 and 180.
    * Northeast boundary `latitude` is between -90 and 90, `longitude` is between -180 and 180.
    * Zoom is between 0 and 22.
    * Pitch is between 0 and 85.
    * Bearing is between -180 and 180.

**Comment by maxkadel** [comment]
Interested in working on this one! 

(also, if you put spaces between the []s you can use the checkmarks)

**Comment by maxkadel** [comment]
If these values aren't set in the theme, what should the defaults be? The current defaults work well with the seed set, which is set to the 2 US coasts. 

![image](https://user-images.githubusercontent.com/45948126/112316292-59c9cf80-8c81-11eb-9215-68f00ea313ad.png)

**Comment by lauramosher** [comment]
@rudokemper Do you have thoughts on this?

**Comment by rudokemper** [comment]
Yep, because of the seed set I think the current defaults are fine. Thanks @maxkadel.
