### ISSUE TITLE
[Rails][Administrate] For the dashboards, add a dropdown menu to select results per page

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#648]
## Context:
Right now, the Speakers, Stories, and Places dashboards show 20 results per page. Let's make it possible for the user to change the number of results per page with a helpful dropdown with numeric choices.

## Acceptance criteria:

- [ ] Add a dropdown menu in between the Search field and `New ...` button on the Speakers, Stories, and Places dashboards.
- [ ] Add options 20 (default), 50, 100, and all (where all can be the total # in the database).
- [ ] Choosing one of the options results in the page reloading and showing that number of results.

## Assets
Field should go here:
![image](https://user-images.githubusercontent.com/31662219/132915674-c1eca5b1-38fe-41de-b793-d707cd88293e.png)

**Comment by MohamedAsan** [comment]
I would like to work on this. Kindly assign it to me

**Comment by rudokemper** [comment]
Done; thanks @MohamedAsan!
