### ISSUE TITLE
[Rails][Administrate] Update Theme form labels to be more user-friendly 

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#651]
## Context:
Currently, the Theme field labels are not the most intuitive. Let's change these to the following

## Acceptance criteria:

- [ ] `Background img` - Background image (for welcome screen)
- [ ] `Sponsor logos` - Sponsor logos (for welcome screen)
- [ ] `Mapbox style url` - Mapbox style URL (for online maps)
- [ ] `Mapbox access token` - Mapbox access token associated with the style
- [ ] `Center lat` - Map center, latitude
- [ ] `Center long`- Map center, longitude
- [ ] `Sw boundary lat` - SW bounding box, latitude
- [ ] `Sw boundary long` - SW bounding box, longitude
- [ ] `Ne boundary lat` - NE bounding box, latitude
- [ ] `Ne boundary long` - NE bounding box, longitude
- [ ] `Zoom` - Map zoom level (1 to 22)
- [ ] `Pitch` - Map pitch degree (0 to 90)
- [ ] `Bearing` - Map bearing degree (-180 to 180)

## Assets
![image](https://user-images.githubusercontent.com/31662219/132916202-968f2e76-9f1e-4826-b778-7edb7e44afc5.png)

**Comment by julinvictus** [comment]
Hi I can work on this one
