### ISSUE TITLE
[Rails][Mapbox] Permit null values for the map bounding box in a Community theme

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#703]
Currently, we have some validations set up that forces a numerical value for the bounding box attributes in Theme. These are `sw_boundary_lat`, `sw_boundary_long`, `ne_boundary_lat`, and `nw_boundary_long`. These feed into a bounding box that delimits the maximum limits of where you can pan on the map.

This is a useful thing to have as an option, but we should start with no bounding box to begin with so that the user can pan infinitely across the globe (like so: https://share.getcloudapp.com/NQu7w298).

To make this happen, we first need to allow the user to set null values for these fields in the validations. 
That should allow the map to function as in the example above. 
Lastly, we should have null default bounding box values for a new community (as set in `map_configurable.rb`)..

## Context:
Currently, with the standard map default bounding box values set in `map_configurable.rb` ((-85, -180), (85, 180)), we are boxing communities into a rectangular view of the map, which cuts the Pacific ocean in half.

## Acceptance criteria:

- [ ] If there are no values set for the four bounding box attributes, the map should permit infinite horizontal panning across the globe, and not cut off at the Pacific ocean.
- [ ] In the Theme dashboard, a user is able to set _either_ values within the accepted range for coordinates (as set currently in `theme_spec.rb`), or null.
- [ ] When a new community is created, the default bounding box values are null.

**Comment by willeyen** [comment]
I would like to work on this issue, if possible!
