### ISSUE TITLE
[Map] Add ability to set map projection (and prevent new globe projection from temporarily breaking)

### ISSUE THREAD

**Issue by rudokemper** [Terrastories/terrastories#790]
## Context:
Starting from v2.6, Mapbox GL JS supports multiple map projections. This feature allows you to create more accurate visualizations at every zoom level and tell a better story with your data.

We would like to be able to permit a Terrastories community admin user to set the projection for their map.

In addition, the brand new `globe` projection is currently breaking Terrastories. Mapbox introduced this new projection in Mapbox GL JS 2.9, and new maps in Mapbox Studio are created with this projection included by default. Hence, unless we override this projection in Terrastories, these new maps will not load until `mapbox-gl-rails` updates to 2.9. So adding a feature for a Terrastories admin user to set the projection (with a default of `mercator` and a select menu excluding `globe` for the time being) solves this problem as well.

## Acceptance criteria:
- [ ] A new projection field is added to `themes`
- [ ] When a new community is created, the default projection is set to `mercator`
- [ ] An admin user for a community is able to change the projection to the other projections supported as of Mapbox GL JS 2.7 in `Themes` menu.
- [ ] When loading the map, it will be projected using whichever projection is selected by the admin user.
- [ ] Ensure that the projection change works offline with TileServer-GL.
